### ISSUE TITLE
Some works need to be done

### ISSUE THREAD

**Issue by yang-wei** [yang-wei/rd3#1]
- [x] update dependencies (hope to remove both react and d3 from dependencies)
- [x] demo page (is now difficult to maintain)
- [x] documentation (keep using wiki or show more in demo page)
- [x] eslint
- [x] update the original repository about `rd3`
- [x] babel 6 for smaller bytes

**Comment by jonase** [comment]
I looked at possibly helping out with at least the `eslint` part. According to [CONTRIBUTING.md](https://github.com/yang-wei/rd3/blob/master/CONTRIBUTING.md) you'd like to follow the google style guide. With the [eslint-config-google](https://github.com/google/eslint-config-google) rules there are quite a lot of errors/warnings. Many of them are [key-spacing](http://eslint.org/docs/rules/key-spacing) due to [aligning map values](https://github.com/yang-wei/rd3/blob/master/src/mixins/CartesianChartPropsMixin.js#L9-L36). We can either (whatever you'd prefer):
- create a custom rule making this kind of alignment a requirement
- disable the rule, or
- "fix" the code

If you'd like, I can also create a PR with eslint setup so you can see the current warnings/errors and we can later see how to best resolve them.

**Comment by yang-wei** [comment]
I opened a new issue at #10. Let's talk over there =)
 @jonase

**Comment by janaipakos** [comment]
What should the documentation cover?

**Comment by yang-wei** [comment]
@janaipakos 

A demo page like the [current one](https://reactiva.github.io/react-d3-website/) with all the API(props we can pass in from top) covered. By cover I mean list them out and for some difficult API such as `colorAccessor`, example would be neccessary.

If every API can be update/change through form/input then it would be best !

Let me know if you are interested to take over =)

**Comment by yang-wei** [comment]
documentation is out ! 

https://yang-wei.github.io/rd3/
