### ISSUE TITLE
Adding labels and modifying existing ones

### ISSUE THREAD

**Issue by enguerranws** [yang-wei/rd3#37]
Hi,

Thank you really much for this work, very useful and easy to use.

I'm currently working on PieChart, and I'm trying to add/modify some stuff to the basic one: 
- a "total" label (which displays the absolute total of the values used for the chart), in the center of the circle
- adding a background or borders to the existing labels (which may need to add some `<line>` or `<rect>` element

Those are just examples, but what is in your opinion the best way to modify/add shapes in svg in rd3 components?

**Comment by yang-wei** [comment]
> a "total" label (which displays the absolute total of the values used for the chart), in the center of the circle

sound good to use HOC to wrap this since it doesn't related to child

> adding a background or borders to the existing labels (which may need to add some <line> or <rect> element

for this you need to modify this library by yourself. IMO it works best when you can pass the component from top. By this you can style your component as you like.

However all of those thing will be difficult if you need to take care of state (I am still finding my way to make this easier).

So to conclude this
- to add component which do not rely on the child component, use HOC to wrap it. [Like this](https://yang-wei.github.io/rd3/docs/new/responsiveCharts.html)
- to interact with child component, you need to modify this library (either you can modify it directly, or you can make it receive svg shape from top)

(Btw internally I am working on "receive svg shape from top")
